# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Debug
    - name: Release
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Pack BiUM.Core
      run: dotnet pack ./src/BiUM.Core/BiUM.Core.csproj --no-build -c Release -o nupkg

    - name: Upload BiUM.Core Artifact
      uses: actions/upload-artifact@v3
      with:
        name: BiUM.Core
        path: ./src/BiUM.Core/bin/Release/*.nupkg

    - name: Publish BiUM.Core
      run: dotnet nuget push ./src/BiUM.Core/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/FOA-FunctiOnAir/index.json" -k ${{ secrets.GITHUB_TOKEN }}

    - name: Pack BiUM.Infrastructure
      run: dotnet pack ./src/BiUM.Infrastructure/BiUM.Infrastructure.csproj --no-build -c Release -o nupkg

    - name: Upload BiUM.Infrastructure Artifact
      uses: actions/upload-artifact@v3
      with:
        name: BiUM.Infrastructure
        path: ./src/BiUM.Infrastructure/bin/Release/*.nupkg

    - name: Publish BiUM.Infrastructure
      run: dotnet nuget push ./src/BiUM.Infrastructure/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/FOA-FunctiOnAir/index.json" -k ${{ secrets.GITHUB_TOKEN }}
